#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
pkg_dependencies="apache2-utils automake htop build-essential curl gawk git libcppunit-dev libcurl4-openssl-dev libncurses5-dev libsigc++-2.0-dev libsox-fmt-all libsox-fmt-mp3 libssl-dev libtool mktorrent net-tools nginx php7.3 php7.3-cli php7.3-common php7.3-curl php7.3-fpm php7.3-json php7.3-mbstring php7.3-opcache php7.3-readline php7.3-xml php-geoip pkg-config psmisc python-pip screen subversion unzip sox vim zip zlib1g-dev apt-transport-https gnupg2"

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors


#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
appli=$YNH_APP_INSTANCE_NAME
data_dir="/home/yunohost.rutorrent"
#passw=$4
current_dir=${PWD}
#debian_version=$(lsb_release -c -s)


#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
#=================================================

ynh_script_progression --message="Validating installation parameters..."

# Register (book) web path
ynh_webpath_register --app=$appLI --domain=$domain --path_url=$path


#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_script_progression --message="Storing installation settings..." --weight=2
ynh_app_setting_set --app=$appli --key=domain --value=$domain
ynh_app_setting_set --app=$appli --key=path --value=$path


#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN PORTS
#=================================================

ynh_script_progression --message="Configuring firewall..." --weight=16

# Find a free port
port=$(ynh_find_port --port=45069)
# Open this port
ynh_exec_warn_less yunohost firewall allow --no-upnp TCP $port
ynh_app_setting_set --app=$app --key=port --value=$port


#=================================================
# INSTALL TRANSMISSION
#=================================================
ynh_script_progression --message="Installing Rutorrent..." --weight=16

ynh_install_app_dependencies $pkg_dependencies
ynh_install_extra_app_dependencies --repo="deb http://ftp2.fr.debian.org/debian/ buster main non-free" --package="rar unrar"
ynh_install_extra_app_dependencies --repo="deb http://mediaarea.net/repo/deb/debian/ buster main" --key="http://mediaarea.net/repo/deb/debian/pubkey.gpg" --package="mediainfo"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=2

# Create a dedicated NGINX config
ynh_add_nginx_config


#=================================================
# SPECIFIC SETUP
#=================================================
# CREATE DIRECTORIES
#=================================================

mkdir -p "/home/$data_dir/{progress,completed,watched}"


# Build xmlrpc
cd /tmp
git clone https://github.com/mirror/xmlrpc-c.git
cd xmlrpc-c/stable/
./configure
make
make install

# Build libtorrent
cd /tmp
git clone https://github.com/rakshasa/libtorrent.git
cd libtorrent
git checkout v0.13.8
./autogen.sh
./configure --disable-debug
make
make install

# Build rtorrent
cd /tmp
git clone https://github.com/rakshasa/rtorrent.git
cd rtorrent
git checkout 0.9.8
./autogen.sh
./configure --with-xmlrpc-c --with-ncurses --disable-debug
make
make install

ldconfig

# Install rutorrent
git clone https://github.com/Novik/ruTorrent.git /var/www/rutorrent

# Installation cloudscraper pour plugin _cloudflare
pip install cloudscraper

# Installation du plugin ruTorrent ratiocolor
cd /var/www/rutorrent/plugins/
git clone https://github.com/Micdu70/rutorrent-ratiocolor.git ratiocolor

# Installation du plugin ruTorrent Logoff
cd /var/www/rutorrent/plugins/
wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-logoff/logoff-1.3.tar.gz 2>&1
tar xzfv  logoff-1.3.tar.gz
rm logoff-1.3.tar.gz

# Installation du plugin GeoIP2
cd /var/www/rutorrent/plugins/
git clone https://github.com/Micdu70/geoip2-rutorrent.git geoip2

# Installation du plugin ruTorrent pausewebui
cd /var/www/rutorrent/plugins/
wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-pausewebui/pausewebui.1.2.zip 2>&1
unzip pausewebui.1.2.zip
ynh_secure_remove --file=__MACOSX pausewebui.1.2.zip

# Installation du plugin ruTorrent pausewebui
cd /tmp
git clone https://github.com/Micdu70/rutorrent-thirdparty-plugins.git
cd rutorrent-thirdparty-plugins
mv filemanager /var/www/rutorrent/plugins/filemanager

# Changement de propriétaire des fichiers web
chown -R www-data:www-data /var/www/rutorrent


# Configure plugins
cd $current_dir

rm /var/www/rutorrent/plugins/create/conf.php
cp ../sources/plugins/create/conf.php /var/www/rutorrent/plugins/create/conf.php

rm /var/www/rutorrent/plugins/filemanager/conf.php
cp ../sources/plugins/filemanager/conf.php /var/www/rutorrent/plugins/filemanager/conf.php

# Configure nginx
#sed -i "s@PATHTOCHANGE@$path@g" ../sources/nginx/rutorrent.conf
#cp ../sources/nginx/rutorrent.conf /etc/nginx/conf.d/$domain.d/rutorrent.conf

# Create data dir
mkdir $data_dir
mkdir $data_dir/watch
mkdir $data_dir/downloads
mkdir $data_dir/.session

# Create rtorrent user
useradd -p $(openssl passwd -1 $passw) -m rtorrent

# Add rtorrent config
sed -i "s@DATA_DIR@$data_dir@g" ../sources/rtorrent/rtorrent.rc
cp ../sources/rtorrent/rtorrent.rc /home/rtorrent/.rtorrent.rc
chown -R rtorrent:www-data /home/rtorrent/.rtorrent.rc

chown -R rtorrent:www-data $data_dir
chmod 755 $data_dir

# Configure rutorrent
sed -i "s@DATA_DIR@$data_dir@g" ../sources/rutorrent/config.php
cp ../sources/rutorrent/config.php /var/www/rutorrent/conf/config.php
chown -R www-data:www-data /var/www/rutorrent

# Launch rtorrent on boot
cp ../sources/init/rtorrent /etc/init.d/rtorrent
chmod +x /etc/init.d/rtorrent
update-rc.d rtorrent defaults

# Start rtorrent
ynh_systemd_action --service-name=rtorrent --action=start
yunohost app ssowatconf
ynh_systemd_action --service_name=nginx --action=reload



# Register the service on yunohost
yunohost service add rtorrent --description="Rutorrent"
