#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
data_dir=$3
passw=$4
current_dir=${PWD}
debian_version=$(lsb_release -c -s)

# Source app helpers
source /usr/share/yunohost/helpers

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a rutorrent
if [[ ! $? -eq 0 ]]; then
  echo "Error: domain/path not available"
  exit 1
fi


# Install source Rutorrent
ynh_package_is_installed "rutorrent"

if ! ynh_package_is_installed "rutorrent" ; then
  echo "Oups, le paquet n'est pas installé."
else
  echo "Le paquet est installé !"
fi

if [ "$debian_version" = "buster" ]; then
  cd /tmp
    
  if [ -f /etc/apt/sources.list.d/rutorrent.list ]; then
    sudo rm /etc/apt/sources.list.d/rutorrent.list
  fi

  apt install -y apt-transport-https gnupg2
  echo "#Depot sury-php
deb https://packages.sury.org/php/ buster main" >> /etc/apt/sources.list.d/sury-php.list

  echo "#Depot paquets proprietaires
deb http://ftp2.fr.debian.org/debian/ buster main non-free
deb-src http://ftp2.fr.debian.org/debian/ buster main non-free" >> /etc/apt/sources.list.d/non-free.list

  echo "#Depot multimedia
deb http://www.deb-multimedia.org buster main non-free" >> /etc/apt/sources.list.d/multimedia.list

  echo "#Depot mediainfo
deb http://mediaarea.net/repo/deb/debian/ buster main" >> /etc/apt/sources.list.d/mediainfo.list

  wget https://packages.sury.org/php/apt.gpg -O sury.gpg && apt-key add sury.gpg

  wget http://mediaarea.net/repo/deb/debian/pubkey.gpg -O mediainfo.gpg && apt-key add mediainfo.gpg

fi

# Install dependencies
sudo apt-get update -oAcquire::AllowInsecureRepositories=true
sudo apt install -y --allow-unauthenticated deb-multimedia-keyring
sudo apt update

sudo apt install -y \
  apache2-utils \
  automake \
  htop \
  build-essential \
  curl \
  ffmpeg \
  gawk \
  git \
  libcppunit-dev \
  libcurl4-openssl-dev \
  libncurses5-dev \
  libsigc++-2.0-dev \
  libsox-fmt-all \
  libsox-fmt-mp3 \
  libssl-dev \
  libtool \
  mediainfo \
  mktorrent \
  net-tools \
  nginx \
  php7.3 \
  php7.3-cli \
  php7.3-common \
  php7.3-curl \
  php7.3-fpm \
  php7.3-json \
  php7.3-mbstring \
  php7.3-opcache \
  php7.3-readline \
  php7.3-xml \
  php-geoip \
  pkg-config \
  psmisc \
  python-pip \
  rar \
  screen \
  subversion \
  unrar \
  unzip \
  sox \
  vim \
  zip \
  zlib1g-dev

# Build xmlrpc
cd /tmp
sudo git clone https://github.com/mirror/xmlrpc-c.git
sudo cd xmlrpc-c/stable/
sudo ./configure
sudo make
sudo make install

# Build libtorrent
cd /tmp
sudo git clone https://github.com/rakshasa/libtorrent.git
cd libtorrent
sudo git checkout v0.13.8
sudo ./autogen.sh
sudo ./configure --disable-debug
sudo make
sudo make install

# Build rtorrent
cd /tmp
sudo git clone https://github.com/rakshasa/rtorrent.git
cd rtorrent
sudo git checkout 0.9.8
sudo ./autogen.sh
sudo ./configure --with-xmlrpc-c --with-ncurses --disable-debug
sudo make
sudo make install

sudo ldconfig

# Install rutorrent
sudo git clone https://github.com/Novik/ruTorrent.git /var/www/rutorrent

# Installation cloudscraper pour plugin _cloudflare
sudo pip install cloudscraper

# Installation du plugin ruTorrent ratiocolor
cd /var/www/rutorrent/plugins/
sudo git clone https://github.com/Micdu70/rutorrent-ratiocolor.git ratiocolor

# Installation du plugin ruTorrent Logoff
cd /var/www/rutorrent/plugins/
sudo wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-logoff/logoff-1.3.tar.gz
sudo tar xzfv  logoff-1.3.tar.gz
sudo rm logoff-1.3.tar.gz

# Installation du plugin GeoIP2
cd /var/www/rutorrent/plugins/
sudo git clone https://github.com/Micdu70/geoip2-rutorrent.git geoip2

# Installation du plugin ruTorrent pausewebui
cd /var/www/rutorrent/plugins/
sudo wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-pausewebui/pausewebui.1.2.zip
sudo unzip pausewebui.1.2.zip
sudo rm -R  __MACOSX pausewebui.1.2.zip

# Installation du plugin ruTorrent pausewebui
cd /tmp
sudo git clone https://github.com/Micdu70/rutorrent-thirdparty-plugins.git
cd rutorrent-thirdparty-plugins
sudo mv filemanager /var/www/rutorrent/plugins/filemanager

# Changement de propriétaire des fichiers web
sudo chown -R www-data:www-data /var/www/rutorrent


# Configure plugins
cd $current_dir

sudo rm /var/www/rutorrent/plugins/create/conf.php
sudo cp ../sources/plugins/create/conf.php /var/www/rutorrent/plugins/create/conf.php

sudo rm /var/www/rutorrent/plugins/filemanager/conf.php
sudo cp ../sources/plugins/filemanager/conf.php /var/www/rutorrent/plugins/filemanager/conf.php

# Configure nginx
sudo sed -i "s@PATHTOCHANGE@$path@g" ../sources/nginx/rutorrent.conf
sudo cp ../sources/nginx/rutorrent.conf /etc/nginx/conf.d/$domain.d/rutorrent.conf

# Create data dir
sudo mkdir $data_dir
sudo mkdir $data_dir/watch
sudo mkdir $data_dir/downloads
sudo mkdir $data_dir/.session

# Create rtorrent user
sudo useradd -p $(openssl passwd -1 $passw) -m rtorrent

# Add rtorrent config
sudo sed -i "s@DATA_DIR@$data_dir@g" ../sources/rtorrent/rtorrent.rc
sudo cp ../sources/rtorrent/rtorrent.rc /home/rtorrent/.rtorrent.rc
sudo chown -R rtorrent:www-data /home/rtorrent/.rtorrent.rc

sudo chown -R rtorrent:www-data $data_dir
sudo chmod 755 $data_dir

# Configure rutorrent
sudo sed -i "s@DATA_DIR@$data_dir@g" ../sources/rutorrent/config.php
sudo cp ../sources/rutorrent/config.php /var/www/rutorrent/conf/config.php
sudo chown -R www-data:www-data /var/www/rutorrent

# Check port availability
sudo yunohost app checkport 45069
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Open port in firewall
sudo yunohost firewall allow TCP 45069 > /dev/null 2>&1

# Launch rtorrent on boot
sudo cp ../sources/init/rtorrent /etc/init.d/rtorrent
sudo chmod +x /etc/init.d/rtorrent
sudo update-rc.d rtorrent defaults

# Start rtorrent
sudo service rtorrent start
sudo yunohost app ssowatconf
sudo service nginx reload

# Save config
sudo yunohost app setting rutorrent data_dir -v $data_dir
sudo yunohost app setting rutorrent path -v $path




# Register the service on yunohost
sudo yunohost service add rtorrent
